# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsq < Formula
  desc "TaskSquad Daemon"
  homepage "https://tasksquad.ai"
  version "0.2.27"

  on_macos do
    on_intel do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.27/tsq_Darwin_x86_64.tar.gz"
      sha256 "7570cade4b3a2df4554cde8e681f51138fa3eb1fefeb9a324a8e94322517fccb"

      def install
        bin.install "tsq"
      end
    end
    on_arm do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.27/tsq_Darwin_arm64.tar.gz"
      sha256 "a15822b915ac7256c700bd3e8fbb0700bdd5f151a71a5b7da1a9d77236ae158c"

      def install
        bin.install "tsq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.27/tsq_Linux_x86_64.tar.gz"
        sha256 "219a710b9468936b2adbda5b66cca2cca3ff1ea700ea7330e93a3974219eb623"

        def install
          bin.install "tsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.27/tsq_Linux_arm64.tar.gz"
        sha256 "73106b1e896978029c3b6044ec91a6cb508ed5ed869d332a28b2da08a7f1d2c0"

        def install
          bin.install "tsq"
        end
      end
    end
  end

  test do
    system "#{bin}/tsq --version"
  end
end
