# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsq < Formula
  desc "TaskSquad Daemon"
  homepage "https://tasksquad.ai"
  version "0.2.31"

  on_macos do
    on_intel do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.31/tsq_Darwin_x86_64.tar.gz"
      sha256 "52f1ccff3b05c5eddf6f6a9db02ceaa2e2d900261586277af6acb19083329461"

      def install
        bin.install "tsq"
      end
    end
    on_arm do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.31/tsq_Darwin_arm64.tar.gz"
      sha256 "71ae190658faf2d7686143a834cccad629c7aee05eecced4eec791beec260f16"

      def install
        bin.install "tsq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.31/tsq_Linux_x86_64.tar.gz"
        sha256 "cb7949a0a3413205584814428a065891ae0ff6eb07d36fcefd078633f045899c"

        def install
          bin.install "tsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.31/tsq_Linux_arm64.tar.gz"
        sha256 "97c0c9b5ac3a1453d6626b2d9f556c518db9f78ab7b66b82bdac9ebc2152b7ed"

        def install
          bin.install "tsq"
        end
      end
    end
  end

  test do
    system "#{bin}/tsq --version"
  end
end
