# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsq < Formula
  desc "TaskSquad Daemon"
  homepage "https://tasksquad.ai"
  version "0.2.10"

  on_macos do
    on_intel do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.10/tsq_Darwin_x86_64.tar.gz"
      sha256 "83a7ee545ca627b022b5fc9fe66b0b771bdd97fa4ecebeced882267cdd15bcd8"

      def install
        bin.install "tsq"
      end
    end
    on_arm do
      url "https://github.com/xajik/tasksquad/releases/download/v0.2.10/tsq_Darwin_arm64.tar.gz"
      sha256 "1eb7db68934f0f99238c4a023f5e32285a30a5bfedbe255862285b8f5ecaa557"

      def install
        bin.install "tsq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.10/tsq_Linux_x86_64.tar.gz"
        sha256 "540ac347ee2f04d7fe8ea59576c7b58884382e3afd2e2d9a043cad51c871ceee"

        def install
          bin.install "tsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xajik/tasksquad/releases/download/v0.2.10/tsq_Linux_arm64.tar.gz"
        sha256 "78e8ff41a75dcd6cbbd5bb5e2a5d9a46226526abdd6d0746fe5c37edcb8d7b4f"

        def install
          bin.install "tsq"
        end
      end
    end
  end

  test do
    system "#{bin}/tsq --version"
  end
end
